### ISSUE TITLE
prod build - cache control

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/gopherpen#5]
Wondering, if for PROD, does it make sense to have cache set to zero Max age for client ?
At the moment, for PROD, its zero max age and 101 kb.

For DEV, yes makes sense.

**Comment by dmitshur** [comment]
Can you elaborate on the details please?

Where is the cache max age currently set for production build, if at all, and where do you propose it should be set?

**Comment by dmitshur** [comment]
I now understand what you meant @joeblew99. You're proposing setting a `Cache-Control` header with a value of `max-age` higher than 0 for production build. Currently, that header is not set, so a default value of 0 for `max-age` is assumed by clients.

I think that doing that makes sense. In a production build, the static content served is not going to change, not until a new binary is compiled and the process is restarted.

However, I think this project is meant to be a very simple and short starting template, and it doesn't try very hard to optimize (because that'd be added code and complexity). So it might be okay to leave that out. Either way.

> 101 kb.

Note that last-modified header is set, so all queries should be returning 304 if the client supports caching. So the response would be a few bytes, it would not include the entire payload.

What do you think? Are you interested in making a PR to resolve this, or do you think we should just leave this?
